

CREATE TABLE MASTER_BOOKS
(
  ISBN int NOT NULL,
  TITLE varchar(255),
  PUBLISHER varchar(255),
  PRIMARY KEY(ISBN) 
);

CREATE TABLE AUTHORS
(
  AUTHOR_ID int NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME varchar(255) NOT NULL,
  PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE CATEGORIES
(
  CATEGORY_ID int NOT NULL AUTO_INCREMENT,
  CATEGORY_NAME varchar(255),
  PRIMARY KEY(CATEGORY_ID)
);

CREATE TABLE BOOKS
(
  BOOK_ID int NOT NULL AUTO_INCREMENT,
  ISBN int NOT NULL,
  STATUS int,
  ISSUE_DATE timestamp,
  DEPOSIT_DATE timestamp,
  PRIMARY KEY (BOOK_ID),
  FOREIGN KEY(ISBN) REFERENCES MASTER_BOOKS(ISBN)
);



CREATE TABLE AUTHOR_ISBN
(
  AUTHOR_ID int NOT NULL,
  ISBN int NOT NULL,
  FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
  FOREIGN KEY(ISBN) REFERENCES MASTER_BOOKS(ISBN)
);

CREATE TABLE CATEGORY_ISBN
(
  CATEGORY_ID INT NOT NULL, 
  ISBN int NOT NULL,
  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
  FOREIGN KEY(ISBN) REFERENCES MASTER_BOOKS(ISBN)
);


  
  